language: java
script: 'git log --format=%s HEAD~1..HEAD | grep "fixes #" >/dev/null && mvn -e integration-test || mvn -e test'

install: echo 'Skipping mvn install'
 
branches:
  only:
    - dev_1.0.0

before_script:
  - mysql -e 'create user tucana@localhost identified by "tucana";'
