language: java
script: 'git log --format=%s HEAD~1..HEAD | grep "fixes #" >/dev/null && mvn -e integration-test || mvn -e test'

branches:
  only:
    - dev_1.0.0

mysql:
  adapter: mysql2
  database: myapp_test
  username: root
  encoding: utf8
  
before_script:
	- "mysql -e 'create user tucana@localhost identified by \'tucana\';'"