
INSERT INTO CONSTELLATIONS VALUES(null, 'Puppis', 'pup', 'Puppis', 'S', 'Lacaille', 1763, 673.434, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Aquila', 'aql', 'Aquilae', 'N S', 'Ptolemäus', 150, 652.473, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Ara', 'ara', 'Arae', 'S', 'Ptolemäus', 150, 237.057, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Andromeda', 'and', 'Andromedae', 'N', 'Ptolemäus', 150, 722.278, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Bootes / Boötes', 'boo', 'Bootis / Boötis [Anm 1]', 'N', 'Ptolemäus', 150, 906.831, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Crater', 'crt', 'Crateris', 'S', 'Ptolemäus', 150, 282.398, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Sculptor', 'scl', 'Sculptoris', 'S', 'Lacaille', 1756, 474.764, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Chamaeleon', 'cha', 'Chamaeleontis', 'S', 'Bayer', 1603, 131.592, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Fornax', 'for', 'Fornacis', 'S', 'Lacaille', 1756, 397.502, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Delphinus', 'del', 'Delphini', 'N', 'Ptolemäus', 150, 188.549, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Draco', 'dra', 'Draconis', 'N', 'Ptolemäus', 150, 1082.952, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Triangulum', 'tri', 'Trianguli', 'N', 'Ptolemäus', 150, 131.847, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Lacerta', 'lac', 'Lacertae', 'N', 'Hevelius', 1687, 200.688, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Monoceros', 'mon', 'Monocerotis', 'S N', 'Plancius', 1623, 481.569, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Eridanus', 'eri', 'Eridani', 'Sn', 'Ptolemäus', 150, 1137.919, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Pisces', 'psc', 'Piscium', 'Ns', 'Ptolemäus', 150, 889.417, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Musca', 'mus', 'Muscae', 'S', 'Bayer', 1603, 138.355, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Volans', 'vol', 'Volantis', 'S', 'Bayer', 1603, 141.354, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Vulpecula', 'vul', 'Vulpeculae', 'N', 'Hevelius', 1690, 268.165, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Auriga', 'aur', 'Aurigae', 'N', 'Ptolemäus', 150, 657.438, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Equuleus', 'equ', 'Equulei', 'N', 'Ptolemäus', 150, 71.641, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Camelopardalis', 'cam', 'Camelopardalis', 'N', 'Plancius', 1613, 756.828, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Caelum', 'cae', 'Caeli', 'S', 'Lacaille', 1752, 124.865, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Ursa Major', 'uma', 'Ursae Majoris', 'N', 'Ptolemäus', 150, 1279.66, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Canis Major', 'cma', 'Canis Majoris', 'S', 'Ptolemäus', 150, 380.118, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Coma Berenices', 'com', 'Comae Berenices', 'N', 'Brahe', 1590, 386.475, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Lepus', 'lep', 'Leporis', 'S', 'Ptolemäus', 150, 290.291, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Hercules', 'her', 'Herculis', 'N', 'Ptolemäus', 150, 1225.148, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Indus', 'ind', 'Indi', 'S', 'Bayer', 1603, 294.006, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Canes Venatici', 'cvn', 'Canum Venaticorum', 'N', 'Hevelius', 1690, 465.194, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Virgo', 'vir', 'Virginis', 'S N', 'Ptolemäus', 150, 1294.428, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Cassiopeia', 'cas', 'Cassiopeiae', 'N', 'Ptolemäus', 150, 598.407, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Cepheus', 'cep', 'Cephei', 'N', 'Ptolemäus', 150, 587.787, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Carina', 'car', 'Carinae', 'S', 'Lacaille', 1763, 494.184, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Hydrus', 'hyi', 'Hydri', 'S', 'Bayer', 1603, 243.035, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Ursa Minor', 'umi', 'Ursae Minoris', 'N', 'Ptolemäus', 150, 255.864, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Canis Minor', 'cmi', 'Canis Minoris', 'Ns', 'Ptolemäus', 150, 183.367, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Leo Minor', 'lmi', 'Leonis Minoris', 'N', 'Hevelius', 1687, 231.956, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Grus', 'gru', 'Gruis', 'S', 'Bayer', 1603, 365.513, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Cancer', 'cnc', 'Cancri', 'N', 'Ptolemäus', 150, 505.872, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Crux', 'cru', 'Crucis', 'S', 'Plancius', 1589, 68.447, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Lyra', 'lyr', 'Lyrae', 'N', 'Ptolemäus', 150, 286.476, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Leo', 'leo', 'Leonis', 'Ns', 'Ptolemäus', 150, 946.964, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Lynx', 'lyn', 'Lyncis', 'N', 'Hevelius', 1690, 545.386, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Antlia', 'ant', 'Antliae', 'S', 'Lacaille', 1752, 238.901, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Pictor', 'pic', 'Pictoris', 'S', 'Lacaille', 1752, 246.739, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Microscopium', 'mic', 'Microscopii', 'S', 'Lacaille', 1752, 209.513, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Reticulum', 'ret', 'Reticuli', 'S', 'Lacaille', 1752, 113.936, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Corona Borealis', 'crb', 'Coronae Borealis', 'N', 'Ptolemäus', 150, 178.71, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Octans', 'oct', 'Octantis', 'S', 'Lacaille', 1752, 291.045, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Orion', 'ori', 'Orionis', 'N S', 'Ptolemäus', 150, 594.12, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Apus', 'aps', 'Apodis', 'S', 'Bayer', 1603, 206.327, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Pegasus', 'peg', 'Pegasi', 'N', 'Ptolemäus', 150, 1120.794, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Horologium', 'hor', 'Horologii', 'S', 'Lacaille', 1752, 248.885, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Perseus', 'per', 'Persei', 'N', 'Ptolemäus', 150, 614.997, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Pavo', 'pav', 'Pavonis', 'S', 'Bayer', 1603, 377.666, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Sagitta', 'sge', 'Sagittae', 'N', 'Ptolemäus', 150, 79.923, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Phoenix', 'phe', 'Phoenicis', 'S', 'Bayer', 1603, 469.319, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Corvus', 'crv', 'Corvi', 'S', 'Ptolemäus', 150, 183.801, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Pyxis', 'pyx', 'Pyxidis', 'S', 'Lacaille', 1763, 220.833, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Scutum', 'sct', 'Scuti', 'S', 'Hevelius', 1690, 109.114, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Serpens', 'ser', 'Serpentis', 'N S', 'Ptolemäus', 150, 636.928, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Ophiuchus', 'oph', 'Ophiuchi', 'S N', 'Ptolemäus', 150, 948.34, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Sagittarius', 'sgr', 'Sagittarii', 'S', 'Ptolemäus', 150, 867.432, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Cygnus', 'cyg', 'Cygni', 'N', 'Ptolemäus', 150, 803.983, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Dorado', 'dor', 'Doradus', 'S', 'Bayer', 1603, 179.173, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Vela', 'vel', 'Velorum', 'S', 'Lacaille', 1763, 499.649, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Sextans', 'sex', 'Sextantis', 'S N', 'Hevelius', 1690, 313.515, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Scorpius', 'sco', 'Scorpii', 'S', 'Ptolemäus', 150, 496.783, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Capricornus', 'cap', 'Capricorni', 'S', 'Ptolemäus', 150, 413.947, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Taurus', 'tau', 'Tauri', 'Ns', 'Ptolemäus', 150, 797.249, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Corona Australis', 'cra', 'Coronae Australis', 'S', 'Ptolemäus', 150, 127.696, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Piscis Austrinus', 'psa', 'Piscis Austrini', 'S', 'Ptolemäus', 150, 245.375, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Triangulum Australe', 'tra', 'Trianguli Australis', 'S', 'Bayer', 1603, 109.978, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Mensa', 'men', 'Mensae', 'S', 'Lacaille', 1752, 153.484, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Columba', 'col', 'Columbae', 'S', 'Plancius', 1592, 270.184, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Telescopium', 'tel', 'Telescopii', 'S', 'Lacaille', 1756, 251.512, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Tucana', 'tuc', 'Tucanae', 'S', 'Bayer', 1603, 294.557, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Libra', 'lib', 'Librae', 'S', 'Ptolemäus', 150, 538.052, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Cetus', 'cet', 'Ceti', 'Sn', 'Ptolemäus', 150, 1231.411, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Aquarius', 'aqr', 'Aquarii', 'Sn', 'Ptolemäus', 150, 979.854, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Hydra', 'hya', 'Hydrae', 'Sn', 'Ptolemäus', 150, 1302.844, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Aries', 'ari', 'Arietis', 'N', 'Ptolemäus', 150, 441.395, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Norma', 'nor', 'Normae', 'S', 'Lacaille', 1752, 165.29, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Lupus', 'lup', 'Lupi', 'S', 'Ptolemäus', 150, 333.683, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Centaurus', 'cen', 'Centauri', 'S', 'Ptolemäus', 150, 1060.422, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Circinus', 'cir', 'Circini', 'S', 'Lacaille', 1752, 93.353, null );
INSERT INTO CONSTELLATIONS VALUES(null, 'Gemini', 'gem', 'Geminorum', 'N', 'Ptolemäus', 150, 513.761, null );